name: Sync Docs and ReadMe from Private Repo

on:
  workflow_dispatch:  # Allows manual runs from GitHub UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rali-docs
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Token
        run: |
          git config --global url."https://github:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Clone Private Repo Using PAT
        run: |
          git clone https://github.com/IlliquidAsset/rali.git --depth 1
          
          # Ensure docs folder exists before copying
          mkdir -p docs

          # Copy docs if the folder exists in rali
          if [ -d "rali/doc" ]; then
            cp -r rali/doc/* docs/
          else
            echo "No docs folder found in rali, skipping."
          fi

          # Copy README.md only if it exists
          if [ -f "rali/README.md" ]; then
            cp rali/README.md README.md
          else
            echo "README.md not found in rali, skipping."
          fi

          rm -rf rali  # Cleanup

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/ README.md
          git commit -m "Sync latest docs and ReadMe from rali" || echo "No changes to commit"
          git push
