name: Sync Docs from Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rali-docs
        uses: actions/checkout@v3

      - name: Clone Private Repo
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://github.com/your-org/rali.git --depth 1
          cp -r rali/docs/* docs/
          rm -rf rali  # Cleanup

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync latest docs" || echo "No changes to commit"
          git push
