name: Sync Docs and ReadMe from Private Repo

on:
  workflow_dispatch:  # Allows manual runs from GitHub UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rali-docs
        uses: actions/checkout@v3

      - name: Clone Private Repo Using PAT
        env:
          GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://$GH_PAT@github.com/IlliquidAsset/rali.git --depth 1
          cp -r rali/doc/* docs/
          cp rali/README.md README.md  # Sync ReadMe
          rm -rf rali  # Cleanup

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/ README.md
          git commit -m "Sync latest docs and ReadMe from rali" || echo "No changes to commit"
          git push
